language: node_js
node_js:
- '9'
sudo: false
script:
- npm run lint
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local; fi'
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce; fi'

env:
  global:
  #SAUCE_ACCESS_KEY
  - secure: iME63mjMbPrtr3EqKfROFtUYfX8pMz98HfSi49N8LIkWBYxcOeR5h69fkQHZixtc0bUWEP5BTcGkXUK6dYPF2yNjEgf8ac2+v0qRYeS0nVF65FueOhqWayerQ8Q0EIESxznnre8brrVQs7+C+9x0v9xGKRgIfC89dy66t68qM+qncNnUoUneknaeha/47ehGw9pFbH3F0f8k6zoBD6kRxTieYW3EEML9WwTXQum2kgAUAGfXdYsU990q0vHwUxJMltIV3Isd71xIbv3r0VlNRCrqcG3zppNx2mhVykC23WGG/4jgXIC/RNiqIqSXIXK5VK/+jNMRPDRD0k9UcbDtB5eMlO9PSh8b3eenory8EuLSvcTLnUuqtwNPclygzZnhI0szMJZqbZOADRGRsBrh1feq92e77Fyi+KFnDPeBoCD6eDQ7JZtwDle/WllbR7nKQ3zDP+qn7+jebx1HFQZJnh/dmhya6SnpM0tiY5hDbf/wFrJVQVxpxKMx0ETksf/dW13fN00ZiDHIPnjYuuuvNkqFgh6S6T/J0s4nL0qxOcmAIL30LYanFcQbqbnr9CuDhBOJDIZXWejcYT3Vu+pKzGxpLFqo3xQiA4iAZD1dMwyTHMrskEHmGSQvbiPSq3vzTkjsd8th6TDMN9pZWN9Pn4DiwTVomN8ftZIZs2c80Qc=
