language: node_js
node_js:
- '9'
sudo: false
script:
- npm run lint
- if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local;
  fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce;
  fi
env:
  global:
  - secure: THggeaeDcprjgIm8wS26z5xz6qhioeZWOsfxs3/4XbXXcW22X8mvSI1w49Pb9pTW9RoRSCilLtkuF+kG/7/xC1AIoLSvRtRML2rHe8GI9dvBfcTgugY7nPAaF0W4QVBrKgR8IMaTft9ma8zrroOiTwjKlIYhO3doZXeX8pMiRIuG0YDoglQup7AfzWR2nU/GKjRidtsGS4rPp5EB6npRkNcDYlOi26QW4xNDWCK+lJLqvkXUgK0QMns/TId8d427aorH0RH23G0a+3VROIaJJfjwItIV/SrNbKEpL5YB//Yxy/Nv9Q5rYZctJBPlbneo37iZZ5np/GX96XKjsa82kv1bPfPOdPdZCnQO1SfsA1N/RQvIt6rTWN067Jem5oLMAOG5E1ad9hbEM3GmdPjvPoMS2Pn2zTEKys7agS1wLy6uVv7mtiYpx+efFLqKOu/9CZPBZFUTUJn3lcKbMj9uvdxsramw+y0OvpWPZYscV073xta94KYxsSJA9SQKJrvWXultsFRGIoxDq1L0UQUuPGuLW4LNWMLFfaRczW0u6ZVT4T2aScy2fj/KpEX/Bss643oXAROZ+tMN8aXjlrQDmh8Jy0Y7FUvzEACAu14NAnKDtxu2qsQrdd/ts95OEEiQw7qn9ClRAmsObxzsk6h9oVLNgeNRztUIWrv1GM9ykxc=
  - secure: Zhbur91/x4QRkpgzr3THat8chpHJlxdVOhLzHXfkeEQHoN8XaqKq6rWgFIs3+xig8S2fKJ2NfrZoccJ6+bCA7SYr68/ZzSe3xApiUP5oYkWAvXUGYzWdPwb5jguNwwbmtg0P0/WHQd5JET+rPIPkgSbJxDv9wOmNTI3NIFX0yfy8W7tKUQIjqfFSrVPkOPIDxgrpnbFq1W4R7Mwyo4qS+oIMWGnelpjTd4bAeENgL6dfcq3HVkHLsiKZ95X5Qmyb1kDowGJVUIiPr5PUYBo0mQEH3DvKiyPIppK0Pxce8UlZ3kzTTaOOMpo2SBeLxvAzQv5s97InPWNEXL18NswaOVGN+E2Mh+2rQNrnMML8hdrJNKFeXaEHOH8BoLdq+M4zSKu1zjsEIMhx7FycERJPDs/duloIm8oqN8yKT0U9VssAUWxcul/n5GE75J3Im8F74lSeFgMGFcp9kUUzxj8gg6ehWSIc6zP7yHuvHJBlm0TjHq8LOiqyocpgIV6sPO6FMovWjGieCjfyDX7AkCy2aFU8slRmn55dYAhq2hucZv6VyiSFnYqtjbx4WbJ19Fsfs9CAvhZ6goPxYLyVBrz9oKewHKwZfBaT3cELEeih6lAhL11jKdUj3XJFcPa+71sK4eish1uVvPKGZ++rjFEhvYWgDI6NpJOIxvePTzIEwbk=
