language: node_js
node_js:
- '9'
sudo: false
script:
- npm run lint
- if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local;
  fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce;
  fi
env:
  global:
  - secure: 0Fq3z07wJyixEdMdjO/08sVFYvIk2E2/ElX3nbulAEiwBXMZ9bXHYsqnZR4FXuLXqmOK559Z12oNt80m85ue1Oentu/Rk3kH8BC2Ntv6OjvW1W8K3mrcTQxE9aMNJwZTOqMT+jMf9xSaRrC+Vmt/4mJG/qQSs8IKgIcrqXk6wzwgDzrTXa59vSAxYpcnAglqR6GAQrb5Pmx39J0NkN9M5F2tAotfn5fXyqo8AOnqsAsWzEx+RTeihsbstm5ggqfaJOxl0Ezrox1nKjcO0kveR0rVTcQ29WD4+3k45Uxc92d+Cv6LnRzzhRPrFwrwO3g9qvPOrgwKgeWgdXG4dIfz3nnQnKI6nNJp71960Ew9X+S2DyIy2RSUST3qahmGPVtvejYC0/BOSmcYPm8AvZ3qePkq5+rcbvJCOdM4zG1YfNDJaI2+V/nHFVrazncNEDg7hHCENRPxKzFynnmwZ3uXEM9t/jHZKW+tF5QdXErpXFnbwRt5Pw3c80ExTGs537/qxSiNle3U68nP5ksM095grXEgx9OpsSoQ/1P1vzVMHYfVXyFexY4npWwQfMs2pQ4ca3rznDznhUTHffKkQEkFiM5nc46iV09Bk81ad3JbuWuB3/jx4e83O1gzp/intHnsYcxxiNBeH+Lo4Xb3w5W/WI+UGvUf+aKwQeKcDQG2vJQ=
  - secure: JnYXnDw605GolRjHfbvGKAkhZu6gsmfArUzhxllwQkSfuwHbwvMPuTgrdbW/wcGUtEEbzRcfsNM9eSf5FIdyT/UNG+4meBKbbTG/hLTE/5u2d3vYPqJdRJl8OPD3Qh0MIm6YQloDXYkgPK8JscnRlUwJIABmRcmPSMSFN6mJ9VJB4pGgHk/YwPXDA1ynnxzwvrG1QKhUduns7GcCdjHvkJJeC577ImCIWqD5OuURPCchG84QTQc7MCc2Jj61dsekaWlRodPkP2sC9Zut+kPB96/d41FlEhRrV5ROXkPNOzMNcU3FVsiwakHCZLQV1SbriLHKf27WS3z6JqQSNy0+gU/I34EpjL+pUZ60UaIGpwiKPPnoGPAQ9B2uLLIV0/AXvg0sinRmA7Wvqt2TGF++f6YOZ7ZljN5qVOxnASDpKSajKlYISgOGsP78RvKnFwYTyx1XCiM+GE5LQPJ39Pf9HEJSSrp0E7PVtaDiLj9LrRanu0Bh8LVqyjC+Yf4fTGw2y6st3LdgXUg/M+PVddKfXAayfMW2M3YHQisxIm19+qGxQvcOMCKT4wOcR10qUMKFSQvd3109/bk8C81icDyS5INoFn/Q5K2yNJfnDBbD8eO+e9izAMk9b61uEhxS/5qbjlwhHuOc7UCsETZRP67e8FafLNiPttvB1yxKKWZv2do=
