language: node_js
node_js:
- '10'
sudo: false
script:
- npm run lint
- if [ $TRAVIS_SECURE_ENV_VARS != false ]; then 
    polymer test --skip-plugin local;
  fi
- if [ $TRAVIS_SECURE_ENV_VARS != true ]; then 
    polymer test --skip-plugin sauce;
  fi
env:
  global:
  - secure: sjiAUsP/vZlfKZu8rE8s/eSLVzhFKDkvCFbuPaC6dkkcuhCOgSWk/PhYmBTsaxU4j47IO9+edkX7wGk3oQaspAV8C1EjGBnh6WnS7tRZAebfDaKie9+4TTKK2h9RmtB8+wcH3pIzpM0mvn1UgRiVLu4AaWZK0Z7FJ+8QCkFH8fHLsPpZ04Jg16DRLDsrdFQLIihTFeQNE7ckfGFJV5s7axJezwc4bIW4AqrRdQC5te7lTpvVX78fdcG+F0uoeqzikfVtllSnBK+USpO76tbL1cOZtxncg17+ZSXpy1hxwRCUq/GiK2W0zYU7SVBrJ9TWRzu75Ppfe5rOCv+qPtJe/wfDcBHvvMvFDnpvGJi30P1eSOEWKvWOzAIul3FyUA2dEyURRHqsjif6GmNE15CpoMNLIaX6R/oacfTieD1Jg4OhbwtIdkcLhnP2kTPfMdEy4z8esCkRn4DCV3D6hdJHj+3KCFjBGA3VOTH64wnBtbJRmXQIfFD5JRyHDYjSSQCHhsC4t6sludbu8oHeA1j+wHF/oaScEWlRwcpFyXBLkkdm/K1XLbI70IlJK/Whg00Dr5vRz/6O8jMbP4HyqnSqFNOD2dl/NXe4eQhieAXTCXRa3s6iLkiWKO29GhBoxbYhLdFLnXoifLzWtfClNBga3XKmDkAed9eqaULIV2qL6IU=
  - secure: LZH+bp+kuO/5dfQ8VVkPp9MmRvNDrk7W0w+Fwa9vdt0RrkBcge3UL8w9OoTaK9nNVJOwNRCsqT7fEjyRGtPoNet8iBE56aBrCMwFv7UvDXIIdHIRaeJ1s+1W3rUBsm9OCYxzpSWwPrOGDhYszRtoBxb3omVd5o5JSbSUXpDA0RN7uIwAiIk9hQajruFsYhbTF6M2nvtJyjm7TvXIKYD1nICIu9bt9elYcCtknxFkmbRZccQTZDI9vjMXUPf6DyK1TrLZbzFgoMj6du7BAtl1saRKmtrzDi3m4W8X7XGBqrUN3jGeMcq0mYPuQgNcHG+f+Sn/u8z0uBRC1d1DzjVyYqy+Xq8RGQ0YZ/2AP5HXDtZ3GXB7BRYvtCDVlmUFkOUjvlr83SC22Jej+wDWn7+ITZ7wDXywfWkQwOH5hGg0i0fiFUzVU4jIf8Y0THdWqLXMtk+hOoCRnQA4Ew8qZ/7YmiBv1lUPlbwu57snAaTWtsiJWw/nFXgDRFrLQrkVI0vrHPGnkRerzoiWPrm0Sofg+kLR7IxvQkgSCWTYrq/vV8/tZY7kJkvuvcweXmf5MnpzxCMdnDgCV7ZK+MBzVrL9CciTy3EELFdLmo2wQdO+VhTAeT/qRKazPBLBjxWtKdbKCArH7ahqPov3UvdqpDPqw8+j8/Srbui4n/bs4WIFgNU=
