language: node_js
node_js:
- '9'
sudo: false
script:
- npm run lint
- if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local;
  fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce;
  fi
env:
  matrix:
  - secure: FJHD2o6MJ+qjR9/W42D/7Hv6mzMbick+s0hofmWDhI8Pl86HUbOvUr+mGbx6b3+HCksmLoimJIwMIm7t/yOykHUHHtQWP8L24Dg4iaZd3aMA+uIsOjYHU2BXXTGi+vPX5z6t3PilwkhWE4r8uEEe/Bbx6PeMGFZFVTmZZzZoYICptGGZWfuuFELPLYddjM9vbYl+0JUegeJHRyCuWSFZT/GF+AJwRwbfpckQIaQXresiij2Hj+VGFmtb2T0p0JR88D7gONZUl3a7XevHeVWs7PtGK1fCdh6AG8HPi1YNJ0VQAHYLPaGqMqGcEZezBsHhjOm+A1xZEkx5DjwARHeTNcJk+R9HJLgCArGLcXSL16UXY4LPs/slgXyUosN5HbDofDnRQu92EPttbwAyF2tkMQ3J9xHPvvHvdSbq93s2bEW7rZ/yvL5OxNuM6ulW6Atk/jf0ABakg7l8Qmphw5bd3tLGOkUbvHGrBOTnKUGTMYu8QyBCqO2UOk6pflaXr69xcAa4cGQ7jp348gXR9WtbToatYQgumP/HcZSt9W7lNuha7/7yWCH7yeT+z16UqeRUPFCb8et6nSgmFQn1s9zcc0B/RX44bDJT3q8NSjv8XZxTkzGiKuoCwPh7aKhmukpGg+afrdizt1GOLFkTihfr/Ecme6yOo8bF+irEJj9zx1c=
  - secure: omP8DwWuavOQdYv85352XDNsGLlKsZ0UXbaIEQkgfiOx8WvVo3WOHPwGlIXF78FzVYokQqEMTjlGnl0vFzVEP2AyvVKSDkN6dRiyUHPzoL/qln8u0qRuoYKgNiYxc/vQ52bs5m/UP4mxl4olmMjriDHbRgPCrXiFWfKVR9K8rcOCreKG2zysrBw/2qblN6cubWxi+i+W8ACa4CDGTv5pRF8hXabe6Xg1CRni00CpjL/EfAbv9Y6YKuLIJ70VsRq7bOgATNEZaqgr2Xp38r01nxFFoCKEwI0C1XbI6ErCEOn/MYHsYCUr2gHmg9VpLRVpqyBIarUf5eHTFGVy7YqrWKBEfp98l9r1QhfdLDtZpnGH2O/U3k38qWO1y4TnRYFOZJnFT4V4Wqi8TVW1rrXsHFSSk3BDAnlrPeE07fvUTo+uiU/7zFlFlWNwKehkLY+fWSQehckbPDNcJkJx5YruiPFJMF9aFqD2A98s36SmCE1jXbGOFigtZaxxGfECCHOVVkhUTOOPw5YM5NlIJ2pur7OF3TXr4Z9gK3Y//qQQyq8ZmFyzG0argn5sIAezh9pTKd7l6o5QRcTb/ttxhNEL0dPkqC3Jy9Ii+xE+zSYNpRQOESgRSsfT1sc7rfBeBb8x/DOM9avt+tNn/tu6c1roNROPUS1QovKNz7RJfU2dBkg=
