language: node_js
node_js: 10
dist: trusty
addons:
  apt:
    update: true
  chrome: stable
sudo: required
branches:
  only:
  - master
  - /^v.*$/
script:
- npm run lint
- npm run test-sauce
after_success:
- frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: d2l-sequence-navigator
  - DEFAULT_INCREMENT: patch
  # SAUCE_ACCESS_KEY
  - secure: sjiAUsP/vZlfKZu8rE8s/eSLVzhFKDkvCFbuPaC6dkkcuhCOgSWk/PhYmBTsaxU4j47IO9+edkX7wGk3oQaspAV8C1EjGBnh6WnS7tRZAebfDaKie9+4TTKK2h9RmtB8+wcH3pIzpM0mvn1UgRiVLu4AaWZK0Z7FJ+8QCkFH8fHLsPpZ04Jg16DRLDsrdFQLIihTFeQNE7ckfGFJV5s7axJezwc4bIW4AqrRdQC5te7lTpvVX78fdcG+F0uoeqzikfVtllSnBK+USpO76tbL1cOZtxncg17+ZSXpy1hxwRCUq/GiK2W0zYU7SVBrJ9TWRzu75Ppfe5rOCv+qPtJe/wfDcBHvvMvFDnpvGJi30P1eSOEWKvWOzAIul3FyUA2dEyURRHqsjif6GmNE15CpoMNLIaX6R/oacfTieD1Jg4OhbwtIdkcLhnP2kTPfMdEy4z8esCkRn4DCV3D6hdJHj+3KCFjBGA3VOTH64wnBtbJRmXQIfFD5JRyHDYjSSQCHhsC4t6sludbu8oHeA1j+wHF/oaScEWlRwcpFyXBLkkdm/K1XLbI70IlJK/Whg00Dr5vRz/6O8jMbP4HyqnSqFNOD2dl/NXe4eQhieAXTCXRa3s6iLkiWKO29GhBoxbYhLdFLnXoifLzWtfClNBga3XKmDkAed9eqaULIV2qL6IU=
  # SAUCE_USERNAME
  - secure: LZH+bp+kuO/5dfQ8VVkPp9MmRvNDrk7W0w+Fwa9vdt0RrkBcge3UL8w9OoTaK9nNVJOwNRCsqT7fEjyRGtPoNet8iBE56aBrCMwFv7UvDXIIdHIRaeJ1s+1W3rUBsm9OCYxzpSWwPrOGDhYszRtoBxb3omVd5o5JSbSUXpDA0RN7uIwAiIk9hQajruFsYhbTF6M2nvtJyjm7TvXIKYD1nICIu9bt9elYcCtknxFkmbRZccQTZDI9vjMXUPf6DyK1TrLZbzFgoMj6du7BAtl1saRKmtrzDi3m4W8X7XGBqrUN3jGeMcq0mYPuQgNcHG+f+Sn/u8z0uBRC1d1DzjVyYqy+Xq8RGQ0YZ/2AP5HXDtZ3GXB7BRYvtCDVlmUFkOUjvlr83SC22Jej+wDWn7+ITZ7wDXywfWkQwOH5hGg0i0fiFUzVU4jIf8Y0THdWqLXMtk+hOoCRnQA4Ew8qZ/7YmiBv1lUPlbwu57snAaTWtsiJWw/nFXgDRFrLQrkVI0vrHPGnkRerzoiWPrm0Sofg+kLR7IxvQkgSCWTYrq/vV8/tZY7kJkvuvcweXmf5MnpzxCMdnDgCV7ZK+MBzVrL9CciTy3EELFdLmo2wQdO+VhTAeT/qRKazPBLBjxWtKdbKCArH7ahqPov3UvdqpDPqw8+j8/Srbui4n/bs4WIFgNU=
  # GITHUB_RELEASE_TOKEN (299c......3309)
  - secure: AcNebl7JRgxfy1HB7mwQko+vD29Wzu9mbtmcG4KAjKhtZ/ppZZ5TWbwBlmW/LHxkLE3tr+JQseTAV8hU3OAdpHm4RwI4dDjJMEV9id8YWCmWXPHjWCwE1QeviErmwjV2xdYk2OCpfAJLBM3T/dM1Q2Z/cDIZbg1yMLGwY7AZ6wjC/rkQvsN4fdFcSTBOtbwB1C2ydmjAO2EIAh5Ninm1JWw3OaBVVzDy0Bo6Wwewn9XD6+lpicGjd71tawhIkzJwVbz86A9/n3Xqb/aiiP95/tY5Py+HCIxA/6RHNcaQpUe4ppSuu9d40SvOUB1VstEHy5KyvCUO9EQMimmn0kwarki1D/QBN5L2yxqUGySpnyzWol7h5qMPRl6VON1z+n+tYE7rBZ+wsI/OaphsMlXyuIUiYH93NYK/LHgalGeTtKjxbfHgc8VggyH7DRe9jdk+YE2T3YKnzePhHul7r88/QLWfND2CQ5yiZU9bkX04lLjV26y1IgIMY71M7XxoCOIJ8gAzJ/TT9dyDLEyKdEuj16G8UtIVxcHSIHAoZNZ8cvxqK8DyHuAaN8rjrjCmOkpt76bfZmGSwrKQhTIZp1lY9TyazWJmttntA9KUpIJSh84hFbBcvt0/PvoKNp868Yk1GuD2XOmXTKcf18T0nETwtlUBdJjawevtGScMW9h4YWM=
