language: node_js
node_js:
- '9'
sudo: false
script:
- npm run lint
- if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local;
  fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce;
  fi
env:
  matrix:
  - secure: 6BPXHqt5GC+iYBYycObLlruPzg/vFh4PfB8j0ttOiiOW78m/9ZFZmvQDCUzTDzZRWge/24byGNHbvDCcKqv5uzoNePQh1XmT3StE9NF8Y7uS/nI17JBH0zJ7DlOeJBlHQO5xFZUyFbUkmLnIAMf/jkUYRblmcTJRcW39vTxPMB4jj1YuUej5JSBtXIeF0wEtwDrTK9r8kaGzC4oSsOkZaPOntP81DRs1LkCKmp4nuW1DnBeY2BVdliimBmDeuvm06NW6ufFzuuIGZFFBFa7KYG9uP7+wMbd3r/sXaOYuzJc7dLZ+svotZr9gRzituOR50nwsDvNJzxiXsNCSjKaqUd7c67lfvKrtSwTTQ5AkFN1t2T5xEKsHWE5XSwyIdwhGnwoswX1x7jhJum0S890jpgOfAm4NFQpEgNEgWoIU6dGJgMP0W2hjyU2G47uT/lcInttA+eRbZWzfbXW061OW1Ubuh5c/EJgD+zaAGPMkO26aGm5xn0t3CjpekHdXQdJ6sj8BOKYp2qkzIsHDiX10k3oJqXqFQYl4FHlv3UKQ9lbBUgOplp5I3UsWFa4/UKJikYCWW/V300S2Ofzj/DIsSFCBQi+n3Yv1XtNFC150XmNNSx0QGaOM2/5h31OJ8oxiE9jZcjxtp8Uvc8NRVFZwAPWWQSgytE1Cv8KZKzMPF1g=
  - secure: ZT3zEqmb3eDKoVYFRRocfVJomuxJO57XUc41zQijdr0tuNfuqLch8YBkWMq3RB95jBUq9HLIXU4FdrJ+bAc/P1rHb/rKIkMOtXpVrU8pod8ZaFBgnHhVja/Z5aduMJlLGEWhF/igXBhNjRDzxc+ntyWQjVHcg1ubM+uMhR1f/b7USGeSE6y0WNZWBdl12GIpfjrXx/xo/pfsJp5e+AG8AuEHC4USi2IwyEtyKWEXQYuFfE+xMrFfwQRwUY+pLjOmehmtg15HBX3pIRNhkJzhMDXnS8OtQcA9A/caykzyaL5EM193PFSgnDtof3qUHZm//u1vLIEYYP9vnumBlScdbYt8ThgTQP5rWz3I4vopAPMwy4q6xRI4GIKsFX3hWBnzYo1WvtyR+TWPj3c7Oip09G72dBjHLw7Yvh9E5RRg0HlK2JDBpiR+4nkaY7nfU4/MV7kOa7HIw/m+qv2l3+KtSokiuCpiNgMH7Lee5WLylwlmtf/QGQnPhzgUvdhZh8/asMuFeThYvUV8kYti0c+qSrLQuaJgspE3qyxtaJjW8OTPpGydbBNn7hpJQmSge/RXBPKI7L/yXdDDlvA7BKhJz0x742/2xZeGOS95lYbTBkfj3Q4Sq+uHu9rDOSUUdUyJDXY2YmM280aXEs9XbYzuHMof89H7C66ido+s/XKo680=
